// GENERATED by gen-build-info.js — do not edit.
// Rewritten on every build; the value is Date.now() at build time.
export const BUILD_TIME_MS = 1791261527639;
// What shared/device-model looked like when this bundle was built (shared/device-model/model-hash.js). tools/check-ui-fresh.js
// compares it to the current one: the model's constants are COPIED into the bundle, so a stale bundle disagrees with the device.
export const MODEL_HASH = '47bac8474998';
